name: Python

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python
        uses: actions/checkout@v2
        with:
          python-version: '3.10.6'
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest